// Code generated by go tool dist; DO NOT EDIT.

package cfg

const DefaultPkgConfig = `pkg-config`
func DefaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "gcc"
	}
	return "aarch64-linux-android-clang"
}
func DefaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "aarch64-linux-android-clang++"
	}
	return "aarch64-linux-android-clang++"
}
