// Code generated by go tool dist; DO NOT EDIT.

package main

const defaultPkgConfig = `pkg-config`
func defaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "gcc"
	}
	return "aarch64-linux-android-clang"
}
func defaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "aarch64-linux-android-clang++"
	}
	return "aarch64-linux-android-clang++"
}
